apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eu6817hpe-python 
  janus-idp.io/tekton: eu6817hpe-python
  backstage.io/kubernetes-id: eu6817hpe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eu6817hpe-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  